#!/usr/bin/env bash
#script that configures a new Ubuntu machine, installing nginx
sudo apt-get update 
sudo apt-get -y install nginx
sudo ufw allow ‘Nginx HTTP’
sudo service nginx start
sudo bash -c ‘echo “service nginx start” >> /etc/rc.local’
