#!/usr/bin/env bash
#Configures Nginx server so that /redirect_me is redirecting to another page.
echo 'location /redirect_me { return 301 https://intranet.alxswe.com; }' | sudo tee -a /etc/nginx/sites-available/default && sudo service nginx reload
