#!/usr/bin/env bash
#Configures Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
echo 'location /redirect_me { return 301 https://intranet.alxswe.com; }' | sudo tee -a /etc/nginx/sites-available/default && sudo service nginx restart
