#!/usr/bin/env bash
#Configures server to include custom header{server name) in response.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i '/listen 80 default_server/a \	rewrite ^/redirect_me https://intranet.alxswe.com/ permanent;' /etc/nginx/sites-available/default
SERVER_NAME=$(hostname)
sudo sed -i "/location \/ {/a \	add_header X-Served-By $SERVER_NAME;" /etc/nginx/sites-available/default
sudo service nginx restart
