#!/usr/bin/env bash
#Configures Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a \	rewrite ^/redirect_me https://intranet.alxswe.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
