#!/usr/bin/env bash
#Configure server to run Nginx as user nginx.

if ! id -u nginx > /dev/null 2>&1; then
    sudo useradd -r -s /bin/false nginx
fi

pkill -f apache2
sudo sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo systemctl restart nginx
